// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/AppendEntriesRPC.proto

package pipe.work;

public final class AppendEntriesRPC {
  private AppendEntriesRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppendEntriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 leaderId = 1;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>required int32 leaderId = 1;</code>
     */
    int getLeaderId();

    /**
     * <code>required .Request request = 2;</code>
     */
    boolean hasRequest();
    /**
     * <code>required .Request request = 2;</code>
     */
    pipe.common.Common.Request getRequest();
    /**
     * <code>required .Request request = 2;</code>
     */
    pipe.common.Common.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    boolean hasTimeStampOnLatestUpdate();
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    long getTimeStampOnLatestUpdate();
  }
  /**
   * Protobuf type {@code AppendEntries}
   */
  public  static final class AppendEntries extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppendEntries)
      AppendEntriesOrBuilder {
    // Use AppendEntries.newBuilder() to construct.
    private AppendEntries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntries() {
      leaderId_ = 0;
      timeStampOnLatestUpdate_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              leaderId_ = input.readInt32();
              break;
            }
            case 18: {
              pipe.common.Common.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(pipe.common.Common.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timeStampOnLatestUpdate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.AppendEntriesRPC.internal_static_AppendEntries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.AppendEntriesRPC.internal_static_AppendEntries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.AppendEntriesRPC.AppendEntries.class, pipe.work.AppendEntriesRPC.AppendEntries.Builder.class);
    }

    private int bitField0_;
    public static final int LEADERID_FIELD_NUMBER = 1;
    private int leaderId_;
    /**
     * <code>required int32 leaderId = 1;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 leaderId = 1;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private pipe.common.Common.Request request_;
    /**
     * <code>required .Request request = 2;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Request request = 2;</code>
     */
    public pipe.common.Common.Request getRequest() {
      return request_ == null ? pipe.common.Common.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>required .Request request = 2;</code>
     */
    public pipe.common.Common.RequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? pipe.common.Common.Request.getDefaultInstance() : request_;
    }

    public static final int TIMESTAMPONLATESTUPDATE_FIELD_NUMBER = 3;
    private long timeStampOnLatestUpdate_;
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public boolean hasTimeStampOnLatestUpdate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timeStampOnLatestUpdate = 3;</code>
     */
    public long getTimeStampOnLatestUpdate() {
      return timeStampOnLatestUpdate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLeaderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStampOnLatestUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, leaderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getRequest());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timeStampOnLatestUpdate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, leaderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeStampOnLatestUpdate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.AppendEntriesRPC.AppendEntries)) {
        return super.equals(obj);
      }
      pipe.work.AppendEntriesRPC.AppendEntries other = (pipe.work.AppendEntriesRPC.AppendEntries) obj;

      boolean result = true;
      result = result && (hasLeaderId() == other.hasLeaderId());
      if (hasLeaderId()) {
        result = result && (getLeaderId()
            == other.getLeaderId());
      }
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasTimeStampOnLatestUpdate() == other.hasTimeStampOnLatestUpdate());
      if (hasTimeStampOnLatestUpdate()) {
        result = result && (getTimeStampOnLatestUpdate()
            == other.getTimeStampOnLatestUpdate());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLeaderId()) {
        hash = (37 * hash) + LEADERID_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderId();
      }
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasTimeStampOnLatestUpdate()) {
        hash = (37 * hash) + TIMESTAMPONLATESTUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimeStampOnLatestUpdate());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.AppendEntriesRPC.AppendEntries prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntries)
        pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.AppendEntriesRPC.AppendEntries.class, pipe.work.AppendEntriesRPC.AppendEntries.Builder.class);
      }

      // Construct using pipe.work.AppendEntriesRPC.AppendEntries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStampOnLatestUpdate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntries_descriptor;
      }

      public pipe.work.AppendEntriesRPC.AppendEntries getDefaultInstanceForType() {
        return pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
      }

      public pipe.work.AppendEntriesRPC.AppendEntries build() {
        pipe.work.AppendEntriesRPC.AppendEntries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.AppendEntriesRPC.AppendEntries buildPartial() {
        pipe.work.AppendEntriesRPC.AppendEntries result = new pipe.work.AppendEntriesRPC.AppendEntries(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeStampOnLatestUpdate_ = timeStampOnLatestUpdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.AppendEntriesRPC.AppendEntries) {
          return mergeFrom((pipe.work.AppendEntriesRPC.AppendEntries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.AppendEntriesRPC.AppendEntries other) {
        if (other == pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance()) return this;
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasTimeStampOnLatestUpdate()) {
          setTimeStampOnLatestUpdate(other.getTimeStampOnLatestUpdate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLeaderId()) {
          return false;
        }
        if (!hasRequest()) {
          return false;
        }
        if (!hasTimeStampOnLatestUpdate()) {
          return false;
        }
        if (!getRequest().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.AppendEntriesRPC.AppendEntries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.AppendEntriesRPC.AppendEntries) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int leaderId_ ;
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000001;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private pipe.common.Common.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder> requestBuilder_;
      /**
       * <code>required .Request request = 2;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public pipe.common.Common.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? pipe.common.Common.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public Builder setRequest(pipe.common.Common.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public Builder setRequest(
          pipe.common.Common.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public Builder mergeRequest(pipe.common.Common.Request value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              request_ != null &&
              request_ != pipe.common.Common.Request.getDefaultInstance()) {
            request_ =
              pipe.common.Common.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public pipe.common.Common.Request.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      public pipe.common.Common.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              pipe.common.Common.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>required .Request request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long timeStampOnLatestUpdate_ ;
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public boolean hasTimeStampOnLatestUpdate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public long getTimeStampOnLatestUpdate() {
        return timeStampOnLatestUpdate_;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder setTimeStampOnLatestUpdate(long value) {
        bitField0_ |= 0x00000004;
        timeStampOnLatestUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timeStampOnLatestUpdate = 3;</code>
       */
      public Builder clearTimeStampOnLatestUpdate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStampOnLatestUpdate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AppendEntries)
    }

    // @@protoc_insertion_point(class_scope:AppendEntries)
    private static final pipe.work.AppendEntriesRPC.AppendEntries DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.AppendEntriesRPC.AppendEntries();
    }

    public static pipe.work.AppendEntriesRPC.AppendEntries getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AppendEntries>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntries>() {
      public AppendEntries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppendEntries(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntries> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntries> getParserForType() {
      return PARSER;
    }

    public pipe.work.AppendEntriesRPC.AppendEntries getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntriesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
     */
    boolean hasIsUpdated();
    /**
     * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated getIsUpdated();
  }
  /**
   * Protobuf type {@code AppendEntriesResponse}
   */
  public  static final class AppendEntriesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppendEntriesResponse)
      AppendEntriesResponseOrBuilder {
    // Use AppendEntriesResponse.newBuilder() to construct.
    private AppendEntriesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesResponse() {
      isUpdated_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntriesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated value = pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                isUpdated_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.AppendEntriesRPC.AppendEntriesResponse.class, pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code AppendEntriesResponse.IsUpdated}
     */
    public enum IsUpdated
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YES = 0;</code>
       */
      YES(0),
      /**
       * <code>NO = 1;</code>
       */
      NO(1),
      ;

      /**
       * <code>YES = 0;</code>
       */
      public static final int YES_VALUE = 0;
      /**
       * <code>NO = 1;</code>
       */
      public static final int NO_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IsUpdated valueOf(int value) {
        return forNumber(value);
      }

      public static IsUpdated forNumber(int value) {
        switch (value) {
          case 0: return YES;
          case 1: return NO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsUpdated>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          IsUpdated> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsUpdated>() {
              public IsUpdated findValueByNumber(int number) {
                return IsUpdated.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final IsUpdated[] VALUES = values();

      public static IsUpdated valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private IsUpdated(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AppendEntriesResponse.IsUpdated)
    }

    private int bitField0_;
    public static final int ISUPDATED_FIELD_NUMBER = 1;
    private int isUpdated_;
    /**
     * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
     */
    public boolean hasIsUpdated() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated getIsUpdated() {
      pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated result = pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated.valueOf(isUpdated_);
      return result == null ? pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated.YES : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsUpdated()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, isUpdated_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, isUpdated_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.AppendEntriesRPC.AppendEntriesResponse)) {
        return super.equals(obj);
      }
      pipe.work.AppendEntriesRPC.AppendEntriesResponse other = (pipe.work.AppendEntriesRPC.AppendEntriesResponse) obj;

      boolean result = true;
      result = result && (hasIsUpdated() == other.hasIsUpdated());
      if (hasIsUpdated()) {
        result = result && isUpdated_ == other.isUpdated_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsUpdated()) {
        hash = (37 * hash) + ISUPDATED_FIELD_NUMBER;
        hash = (53 * hash) + isUpdated_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.AppendEntriesRPC.AppendEntriesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntriesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntriesResponse)
        pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.AppendEntriesRPC.AppendEntriesResponse.class, pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder.class);
      }

      // Construct using pipe.work.AppendEntriesRPC.AppendEntriesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        isUpdated_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesResponse_descriptor;
      }

      public pipe.work.AppendEntriesRPC.AppendEntriesResponse getDefaultInstanceForType() {
        return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
      }

      public pipe.work.AppendEntriesRPC.AppendEntriesResponse build() {
        pipe.work.AppendEntriesRPC.AppendEntriesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.AppendEntriesRPC.AppendEntriesResponse buildPartial() {
        pipe.work.AppendEntriesRPC.AppendEntriesResponse result = new pipe.work.AppendEntriesRPC.AppendEntriesResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isUpdated_ = isUpdated_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.AppendEntriesRPC.AppendEntriesResponse) {
          return mergeFrom((pipe.work.AppendEntriesRPC.AppendEntriesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.AppendEntriesRPC.AppendEntriesResponse other) {
        if (other == pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance()) return this;
        if (other.hasIsUpdated()) {
          setIsUpdated(other.getIsUpdated());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsUpdated()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.AppendEntriesRPC.AppendEntriesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.AppendEntriesRPC.AppendEntriesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int isUpdated_ = 0;
      /**
       * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
       */
      public boolean hasIsUpdated() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated getIsUpdated() {
        pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated result = pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated.valueOf(isUpdated_);
        return result == null ? pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated.YES : result;
      }
      /**
       * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
       */
      public Builder setIsUpdated(pipe.work.AppendEntriesRPC.AppendEntriesResponse.IsUpdated value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        isUpdated_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .AppendEntriesResponse.IsUpdated isUpdated = 1;</code>
       */
      public Builder clearIsUpdated() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isUpdated_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AppendEntriesResponse)
    }

    // @@protoc_insertion_point(class_scope:AppendEntriesResponse)
    private static final pipe.work.AppendEntriesRPC.AppendEntriesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.AppendEntriesRPC.AppendEntriesResponse();
    }

    public static pipe.work.AppendEntriesRPC.AppendEntriesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AppendEntriesResponse>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesResponse>() {
      public AppendEntriesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppendEntriesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesResponse> getParserForType() {
      return PARSER;
    }

    public pipe.work.AppendEntriesRPC.AppendEntriesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntriesPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    boolean hasUnixTimeStamp();
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    long getUnixTimeStamp();

    /**
     * <code>optional .AppendEntries appendEntries = 2;</code>
     */
    boolean hasAppendEntries();
    /**
     * <code>optional .AppendEntries appendEntries = 2;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntries getAppendEntries();
    /**
     * <code>optional .AppendEntries appendEntries = 2;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder getAppendEntriesOrBuilder();

    /**
     * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
     */
    boolean hasAppendEntriesResponse();
    /**
     * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntriesResponse getAppendEntriesResponse();
    /**
     * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
     */
    pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder getAppendEntriesResponseOrBuilder();

    public pipe.work.AppendEntriesRPC.AppendEntriesPacket.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code AppendEntriesPacket}
   */
  public  static final class AppendEntriesPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppendEntriesPacket)
      AppendEntriesPacketOrBuilder {
    // Use AppendEntriesPacket.newBuilder() to construct.
    private AppendEntriesPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesPacket() {
      unixTimeStamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntriesPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimeStamp_ = input.readInt64();
              break;
            }
            case 18: {
              pipe.work.AppendEntriesRPC.AppendEntries.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((pipe.work.AppendEntriesRPC.AppendEntries) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.AppendEntriesRPC.AppendEntries.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.AppendEntriesRPC.AppendEntries) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.work.AppendEntriesRPC.AppendEntriesResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.work.AppendEntriesRPC.AppendEntriesPacket.class, pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder.class);
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      APPENDENTRIES(2),
      APPENDENTRIESRESPONSE(3),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 2: return APPENDENTRIES;
          case 3: return APPENDENTRIESRESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimeStamp_;
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    public boolean hasUnixTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimeStamp = 1;</code>
     */
    public long getUnixTimeStamp() {
      return unixTimeStamp_;
    }

    public static final int APPENDENTRIES_FIELD_NUMBER = 2;
    /**
     * <code>optional .AppendEntries appendEntries = 2;</code>
     */
    public boolean hasAppendEntries() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .AppendEntries appendEntries = 2;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntries getAppendEntries() {
      if (payloadCase_ == 2) {
         return (pipe.work.AppendEntriesRPC.AppendEntries) payload_;
      }
      return pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
    }
    /**
     * <code>optional .AppendEntries appendEntries = 2;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder getAppendEntriesOrBuilder() {
      if (payloadCase_ == 2) {
         return (pipe.work.AppendEntriesRPC.AppendEntries) payload_;
      }
      return pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
    }

    public static final int APPENDENTRIESRESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
     */
    public boolean hasAppendEntriesResponse() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntriesResponse getAppendEntriesResponse() {
      if (payloadCase_ == 3) {
         return (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_;
      }
      return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
    }
    /**
     * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
     */
    public pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder getAppendEntriesResponseOrBuilder() {
      if (payloadCase_ == 3) {
         return (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_;
      }
      return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAppendEntries()) {
        if (!getAppendEntries().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAppendEntriesResponse()) {
        if (!getAppendEntriesResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimeStamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (pipe.work.AppendEntriesRPC.AppendEntries) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimeStamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (pipe.work.AppendEntriesRPC.AppendEntries) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.work.AppendEntriesRPC.AppendEntriesPacket)) {
        return super.equals(obj);
      }
      pipe.work.AppendEntriesRPC.AppendEntriesPacket other = (pipe.work.AppendEntriesRPC.AppendEntriesPacket) obj;

      boolean result = true;
      result = result && (hasUnixTimeStamp() == other.hasUnixTimeStamp());
      if (hasUnixTimeStamp()) {
        result = result && (getUnixTimeStamp()
            == other.getUnixTimeStamp());
      }
      result = result && getPayloadCase().equals(
          other.getPayloadCase());
      if (!result) return false;
      switch (payloadCase_) {
        case 2:
          result = result && getAppendEntries()
              .equals(other.getAppendEntries());
          break;
        case 3:
          result = result && getAppendEntriesResponse()
              .equals(other.getAppendEntriesResponse());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnixTimeStamp()) {
        hash = (37 * hash) + UNIXTIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUnixTimeStamp());
      }
      switch (payloadCase_) {
        case 2:
          hash = (37 * hash) + APPENDENTRIES_FIELD_NUMBER;
          hash = (53 * hash) + getAppendEntries().hashCode();
          break;
        case 3:
          hash = (37 * hash) + APPENDENTRIESRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getAppendEntriesResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.work.AppendEntriesRPC.AppendEntriesPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntriesPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntriesPacket)
        pipe.work.AppendEntriesRPC.AppendEntriesPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.work.AppendEntriesRPC.AppendEntriesPacket.class, pipe.work.AppendEntriesRPC.AppendEntriesPacket.Builder.class);
      }

      // Construct using pipe.work.AppendEntriesRPC.AppendEntriesPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        unixTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.work.AppendEntriesRPC.internal_static_AppendEntriesPacket_descriptor;
      }

      public pipe.work.AppendEntriesRPC.AppendEntriesPacket getDefaultInstanceForType() {
        return pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance();
      }

      public pipe.work.AppendEntriesRPC.AppendEntriesPacket build() {
        pipe.work.AppendEntriesRPC.AppendEntriesPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.work.AppendEntriesRPC.AppendEntriesPacket buildPartial() {
        pipe.work.AppendEntriesRPC.AppendEntriesPacket result = new pipe.work.AppendEntriesRPC.AppendEntriesPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimeStamp_ = unixTimeStamp_;
        if (payloadCase_ == 2) {
          if (appendEntriesBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = appendEntriesBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (appendEntriesResponseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = appendEntriesResponseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.work.AppendEntriesRPC.AppendEntriesPacket) {
          return mergeFrom((pipe.work.AppendEntriesRPC.AppendEntriesPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.work.AppendEntriesRPC.AppendEntriesPacket other) {
        if (other == pipe.work.AppendEntriesRPC.AppendEntriesPacket.getDefaultInstance()) return this;
        if (other.hasUnixTimeStamp()) {
          setUnixTimeStamp(other.getUnixTimeStamp());
        }
        switch (other.getPayloadCase()) {
          case APPENDENTRIES: {
            mergeAppendEntries(other.getAppendEntries());
            break;
          }
          case APPENDENTRIESRESPONSE: {
            mergeAppendEntriesResponse(other.getAppendEntriesResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimeStamp()) {
          return false;
        }
        if (hasAppendEntries()) {
          if (!getAppendEntries().isInitialized()) {
            return false;
          }
        }
        if (hasAppendEntriesResponse()) {
          if (!getAppendEntriesResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.work.AppendEntriesRPC.AppendEntriesPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.work.AppendEntriesRPC.AppendEntriesPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimeStamp_ ;
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public boolean hasUnixTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public long getUnixTimeStamp() {
        return unixTimeStamp_;
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public Builder setUnixTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimeStamp = 1;</code>
       */
      public Builder clearUnixTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.AppendEntriesRPC.AppendEntries, pipe.work.AppendEntriesRPC.AppendEntries.Builder, pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder> appendEntriesBuilder_;
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public boolean hasAppendEntries() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntries getAppendEntries() {
        if (appendEntriesBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (pipe.work.AppendEntriesRPC.AppendEntries) payload_;
          }
          return pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return appendEntriesBuilder_.getMessage();
          }
          return pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public Builder setAppendEntries(pipe.work.AppendEntriesRPC.AppendEntries value) {
        if (appendEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          appendEntriesBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public Builder setAppendEntries(
          pipe.work.AppendEntriesRPC.AppendEntries.Builder builderForValue) {
        if (appendEntriesBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          appendEntriesBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public Builder mergeAppendEntries(pipe.work.AppendEntriesRPC.AppendEntries value) {
        if (appendEntriesBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance()) {
            payload_ = pipe.work.AppendEntriesRPC.AppendEntries.newBuilder((pipe.work.AppendEntriesRPC.AppendEntries) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            appendEntriesBuilder_.mergeFrom(value);
          }
          appendEntriesBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public Builder clearAppendEntries() {
        if (appendEntriesBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          appendEntriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntries.Builder getAppendEntriesBuilder() {
        return getAppendEntriesFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder getAppendEntriesOrBuilder() {
        if ((payloadCase_ == 2) && (appendEntriesBuilder_ != null)) {
          return appendEntriesBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (pipe.work.AppendEntriesRPC.AppendEntries) payload_;
          }
          return pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntries appendEntries = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.AppendEntriesRPC.AppendEntries, pipe.work.AppendEntriesRPC.AppendEntries.Builder, pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder> 
          getAppendEntriesFieldBuilder() {
        if (appendEntriesBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = pipe.work.AppendEntriesRPC.AppendEntries.getDefaultInstance();
          }
          appendEntriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.AppendEntriesRPC.AppendEntries, pipe.work.AppendEntriesRPC.AppendEntries.Builder, pipe.work.AppendEntriesRPC.AppendEntriesOrBuilder>(
                  (pipe.work.AppendEntriesRPC.AppendEntries) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        onChanged();;
        return appendEntriesBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.AppendEntriesRPC.AppendEntriesResponse, pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder, pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder> appendEntriesResponseBuilder_;
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public boolean hasAppendEntriesResponse() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesResponse getAppendEntriesResponse() {
        if (appendEntriesResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_;
          }
          return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return appendEntriesResponseBuilder_.getMessage();
          }
          return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public Builder setAppendEntriesResponse(pipe.work.AppendEntriesRPC.AppendEntriesResponse value) {
        if (appendEntriesResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          appendEntriesResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public Builder setAppendEntriesResponse(
          pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder builderForValue) {
        if (appendEntriesResponseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          appendEntriesResponseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public Builder mergeAppendEntriesResponse(pipe.work.AppendEntriesRPC.AppendEntriesResponse value) {
        if (appendEntriesResponseBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance()) {
            payload_ = pipe.work.AppendEntriesRPC.AppendEntriesResponse.newBuilder((pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            appendEntriesResponseBuilder_.mergeFrom(value);
          }
          appendEntriesResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public Builder clearAppendEntriesResponse() {
        if (appendEntriesResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          appendEntriesResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder getAppendEntriesResponseBuilder() {
        return getAppendEntriesResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      public pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder getAppendEntriesResponseOrBuilder() {
        if ((payloadCase_ == 3) && (appendEntriesResponseBuilder_ != null)) {
          return appendEntriesResponseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_;
          }
          return pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .AppendEntriesResponse appendEntriesResponse = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.work.AppendEntriesRPC.AppendEntriesResponse, pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder, pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder> 
          getAppendEntriesResponseFieldBuilder() {
        if (appendEntriesResponseBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = pipe.work.AppendEntriesRPC.AppendEntriesResponse.getDefaultInstance();
          }
          appendEntriesResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.work.AppendEntriesRPC.AppendEntriesResponse, pipe.work.AppendEntriesRPC.AppendEntriesResponse.Builder, pipe.work.AppendEntriesRPC.AppendEntriesResponseOrBuilder>(
                  (pipe.work.AppendEntriesRPC.AppendEntriesResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        onChanged();;
        return appendEntriesResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AppendEntriesPacket)
    }

    // @@protoc_insertion_point(class_scope:AppendEntriesPacket)
    private static final pipe.work.AppendEntriesRPC.AppendEntriesPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.work.AppendEntriesRPC.AppendEntriesPacket();
    }

    public static pipe.work.AppendEntriesRPC.AppendEntriesPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AppendEntriesPacket>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesPacket>() {
      public AppendEntriesPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppendEntriesPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesPacket> getParserForType() {
      return PARSER;
    }

    public pipe.work.AppendEntriesRPC.AppendEntriesPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntries_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntriesResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntriesPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n resources/AppendEntriesRPC.proto\032\026reso" +
      "urces/common.proto\"]\n\rAppendEntries\022\020\n\010l" +
      "eaderId\030\001 \002(\005\022\031\n\007request\030\002 \002(\0132\010.Request" +
      "\022\037\n\027timeStampOnLatestUpdate\030\003 \002(\003\"j\n\025App" +
      "endEntriesResponse\0223\n\tisUpdated\030\001 \002(\0162 ." +
      "AppendEntriesResponse.IsUpdated\"\034\n\tIsUpd" +
      "ated\022\007\n\003YES\020\000\022\006\n\002NO\020\001\"\231\001\n\023AppendEntriesP" +
      "acket\022\025\n\runixTimeStamp\030\001 \002(\003\022\'\n\rappendEn" +
      "tries\030\002 \001(\0132\016.AppendEntriesH\000\0227\n\025appendE" +
      "ntriesResponse\030\003 \001(\0132\026.AppendEntriesResp",
      "onseH\000B\t\n\007payloadB\r\n\tpipe.workH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pipe.common.Common.getDescriptor(),
        }, assigner);
    internal_static_AppendEntries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AppendEntries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntries_descriptor,
        new java.lang.String[] { "LeaderId", "Request", "TimeStampOnLatestUpdate", });
    internal_static_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntriesResponse_descriptor,
        new java.lang.String[] { "IsUpdated", });
    internal_static_AppendEntriesPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AppendEntriesPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntriesPacket_descriptor,
        new java.lang.String[] { "UnixTimeStamp", "AppendEntries", "AppendEntriesResponse", "Payload", });
    pipe.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
